variable "env" {}
variable "public_key" {}
variable "private_key" {}
variable "project_id" {}
variable "cluster_name" {}
variable "atlas_region" {}
variable "project_name" {}
variable "atlas_dbpassword" {}
variable "atlas_dbuser" {}
variable "atlas_vpc_cidr" {}
variable "aws_region" {} 
variable "access_key" {} 
variable "secret_key" {}
variable "aws_token" {}
variable "aws_vpc_id" {}
variable "aws_account_id" {} 
variable "aws_cidr" {}